title: Thoughts on Cloud Security and IAM
theme: minima
description: Having been in the IT Security and IAM space for over 15 years this blog is my way to share my experience, knowledge with everyone and also help clarrify my thinking as writing always does.
