title: Thoughts on Cloud Security and IAM
#theme: minima
#description: With 15 years in IT Security and IAM, I share experiences and clarify thoughts through this blog
#description: >- # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
  This site is a blog for Venkat Reddy to share his thoughts on Okta and Identity and Access Management and Cloud Security topics.
google_analytics: G-G46Z41D2CE
linkedin_username: username
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

